plugins {
    alias(libs.plugins.android.test)
    alias(libs.plugins.baseline.profile)
}

android {
    namespace = "com.simon.harmonichackernews.benchmark"
    compileSdk = 37
    targetProjectPath = ":app"

    defaultConfig {
        minSdk = 26
        targetSdk = 37
        testInstrumentationRunner = "androidx.benchmark.junit4.AndroidBenchmarkRunner"
        testInstrumentationRunnerArguments["androidx.benchmark.suppressErrors"] =
                "EMULATOR,DEBUGGABLE,NOT-AOT-COMPILED"
    }

    buildTypes {
        benchmark {
            debuggable = false
            matchingFallbacks.add("release")
        }
    }
}

baselineProfile {
    useConnectedDevices = true
    skipBenchmarksOnEmulator = false
}

dependencies {
    implementation(project(":core"))
    implementation(project(":resources"))
    implementation(project(":ui"))
    implementation(libs.coil)
    implementation(libs.compose.multiplatform.ui)
    implementation(libs.kmpalette.core)
    implementation(libs.ksoup)
    implementation(libs.androidx.benchmark.junit4)
    implementation(libs.androidx.benchmark.macro.junit4)
    implementation(libs.androidx.test.ext.junit)
    implementation(libs.androidx.test.runner)
    implementation(libs.androidx.test.uiautomator)
}
