version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(gradle):"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci):"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
