pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

include ':app'
include ':local_ai_runtime'
include ':shared_resources'
include ':shared_logic'
include ':shared_ui'
include ':desktop_smoke'
rootProject.name = "Harmonic Hacker News"
