import org.jetbrains.kotlin.gradle.dsl.KotlinVersion

plugins {
    alias(libs.plugins.android.dynamic.feature)
}

android {
    namespace = "com.simon.harmonichackernews.localai.runtime"
    compileSdk = 37
    ndkVersion = "29.0.13113456"

    defaultConfig {
        minSdk = 26

        externalNativeBuild {
            cmake {
                arguments "-DCMAKE_BUILD_TYPE=Release"
            }
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }

    buildTypes {
        debugFast {
            initWith(release)
            matchingFallbacks.add("release")
        }

        debugLLM {
            initWith(debug)
            matchingFallbacks.add("debug")
        }

        debugLLMFast {
            initWith(debugFast)
            matchingFallbacks.add("release")
        }

        benchmark {
            initWith(release)
            matchingFallbacks.add("release")
        }
        nonMinifiedBenchmark {
            initWith(benchmark)
            matchingFallbacks.add("benchmark")
            matchingFallbacks.add("release")
        }

        fossRelease {
            initWith(release)
            matchingFallbacks.add("release")
        }

        playRelease {
            initWith(release)
            matchingFallbacks.add("release")
        }
    }

    sourceSets {
        debugLLM {
            kotlin.srcDirs += "src/play/java"
        }
        debugLLMFast {
            kotlin.srcDirs += "src/play/java"
        }
        playRelease {
            kotlin.srcDirs += "src/play/java"
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.22.1"
        }
    }
}

androidComponents {
    beforeVariants(selector().withBuildType("release")) { variantBuilder ->
        variantBuilder.enable = false
    }
}

kotlin {
    compilerOptions {
        languageVersion = KotlinVersion.KOTLIN_2_4
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_11
    }
}

dependencies {
    implementation project(":app")
    implementation project(":core")
    debugLLMImplementation(libs.litertlm)
    debugLLMFastImplementation(libs.litertlm)
    playReleaseImplementation(libs.litertlm)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
